services:
  maven:
    image: maven:3.9.5-eclipse-temurin-21
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8989:8989"
    command: ["sleep", "infinity"]
  # java:
  #   image: eclipse-temurin:21.0.1_12-jre
  #   volumes:
  #     - .:/app
  #   command: ["sleep", "infinity"]
  #   environment:
  #     - JAVA_OPTS="-Xmx1g -Xms1g"